const ExportService = {
    generateCSV: function(data, filename) {
        try {
            const headers = Object.keys(data[0] || {});
            const csvContent = [
                headers.join(','),
                ...data.map(row => 
                    headers.map(header => {
                        const value = row[header];
                        if (typeof value === 'string' && value.includes(',')) {
                            return `"${value}"`;
                        }
                        return value;
                    }).join(',')
                )
            ].join('\n');

            const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
            const link = document.createElement('a');
            const url = URL.createObjectURL(blob);
            link.setAttribute('href', url);
            link.setAttribute('download', filename || 'export.csv');
            link.style.visibility = 'hidden';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            return true;
        } catch (error) {
            console.error('CSV Export Error:', error);
            return false;
        }
    },

    generateJSON: function(data, filename) {
        try {
            const jsonContent = JSON.stringify(data, null, 2);
            const blob = new Blob([jsonContent], { type: 'application/json;charset=utf-8;' });
            const link = document.createElement('a');
            const url = URL.createObjectURL(blob);
            link.setAttribute('href', url);
            link.setAttribute('download', filename || 'export.json');
            link.style.visibility = 'hidden';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            return true;
        } catch (error) {
            console.error('JSON Export Error:', error);
            return false;
        }
    },

    generatePDF: function(title, content, filename) {
        try {
            const htmlContent = `
                <!DOCTYPE html>
                <html>
                <head>
                    <meta charset="UTF-8">
                    <title>${title}</title>
                    <style>
                        body { font-family: Arial, sans-serif; margin: 20px; color: #333; }
                        h1 { color: #8b5cf6; border-bottom: 2px solid #8b5cf6; padding-bottom: 10px; }
                        .content { line-height: 1.6; }
                        .footer { margin-top: 40px; border-top: 1px solid #ddd; padding-top: 10px; font-size: 12px; color: #999; }
                    </style>
                </head>
                <body>
                    <h1>${title}</h1>
                    <div class="content">${content}</div>
                    <div class="footer">Generated by Melo on ${new Date().toLocaleString()}</div>
                </body>
                </html>
            `;

            const blob = new Blob([htmlContent], { type: 'application/pdf' });
            const link = document.createElement('a');
            const url = URL.createObjectURL(blob);
            link.setAttribute('href', url);
            link.setAttribute('download', filename || 'export.pdf');
            link.style.visibility = 'hidden';
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
            return true;
        } catch (error) {
            console.error('PDF Export Error:', error);
            return false;
        }
    },

    exportJournalAsJSON: function(entries) {
        const exportData = {
            app: 'Melo Journal',
            version: '2.0',
            exportDate: new Date().toISOString(),
            totalEntries: entries.length,
            entries: entries.map(entry => ({
                date: entry.timestamp instanceof Date ? entry.timestamp.toISOString() : entry.timestamp,
                mood: entry.mood,
                moodScore: MOOD_SCORE_MAP[entry.mood] || 3,
                text: entry.text
            }))
        };

        return this.generateJSON(exportData, `melo-journal-${new Date().toISOString().split('T')[0]}.json`);
    },

    exportJournalAsCSV: function(entries) {
        const csvData = entries.map(entry => ({
            Date: entry.timestamp instanceof Date ? entry.timestamp.toLocaleDateString() : new Date(entry.timestamp?.seconds * 1000).toLocaleDateString(),
            Time: entry.timestamp instanceof Date ? entry.timestamp.toLocaleTimeString() : new Date(entry.timestamp?.seconds * 1000).toLocaleTimeString(),
            Mood: entry.mood,
            'Mood Score': MOOD_SCORE_MAP[entry.mood] || 3,
            'Journal Entry': entry.text
        }));

        return this.generateCSV(csvData, `melo-journal-${new Date().toISOString().split('T')[0]}.csv`);
    }
};
